### ISSUE TITLE
Add interstitial page after heroku bit

### ISSUE THREAD

**Issue by phae** [codeforamerica/city-analytics-dashboard-setup#3]
So that #1 has somewhere to live.

**Comment by phae** [comment]
@migurski here's the template for that page: https://github.com/codeforamerica/city-analytics-dashboard-setup/blob/contact/templates/done.html

**Comment by migurski** [comment]
Everything is live, merged, and editable here:

https://github.com/codeforamerica/city-analytics-dashboard-setup/blob/13310eb5b8efb80b4e0f6f5cdb14e45c598cbece/templates/done.html#L72
