### ISSUE TITLE
Ping Jack with emails from dashboard installed

### ISSUE THREAD

**Issue by migurski** [codeforamerica/city-analytics-dashboard-setup#4]
Send something to @jmadans when a person sets one up.

**Comment by jmadans** [comment]
@migurski To be clear:  I can get to the data submitted via the google form, but it would be good to get a  ping with the email of the associated  google analytics account used to launch the d-board.

**Comment by migurski** [comment]
Right.

**Comment by migurski** [comment]
Done.

**Comment by jmadans** [comment]
@migurski Might there be a way to include the url for the dashboard that was served in each notification?

Looks like Heroku's data clips might be an easier way to do this. https://blog.heroku.com/archives/2012/2/14/simple_data_sharing_with_data_clips

**Comment by migurski** [comment]
Yeah I can do that, I think.
